project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Profile
      - Publications.qmd
      - Post.qmd
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true


